[package]
name = "raytracer"
version = "0.1.0"
authors = ["Depasse Arthur <arthur.depasse96@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra-glm = "0.7"
rand = "0.7.3"
ndarray = { version= "0.13.1", features= ["rayon"]}
itertools = "0.9.0"
crossbeam-utils = "0.7"